all:
	arm-linux-gnueabihf-gcc -O2 -Wall lcd_fb_bl_test.c -o App_lcd

.PHONY:clean copy 

clean:
	sudo rm ./App_lcd /home/rickyduran/sharedir/App _lcd
copy:
	sudo cp App_lcd /home/rickyduran/sharedir